services:
  api:
    build: .
    image: lyftr-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////data/app.db
      WEBHOOK_SECRET: testsecret
    volumes:
      - data:/data

volumes:
  data:
